stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/your_project/your_repository:$CI_COMMIT_REF_SLUG

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main

test:
  stage: test
  script:
    - docker run --rm $DOCKER_IMAGE pytest
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to production environment..."
    # Add deployment scripts here, e.g., using kubectl, terraform, etc.
  only:
    - main
